// Generated by CoffeeScript 1.8.0
(function() {
  define(function(require) {
    var $;
    $ = require('jquery');
    $("#main").text('Cool, I am from RequestJs');
    return console.log('hello world');
  });

}).call(this);
