// Generated by CoffeeScript 1.8.0
(function() {
  require.config({
    baseUrl: 'js/lib',
    paths: {
      app: '../app/app',
      jquery: 'jquery/dist/jquery.min'
    }
  });

  require(['app'], function() {
    return null;
  });

}).call(this);
